name: Deno CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: v1.0.2
      - run: deno test -A --unstable src/kosmos/__tests__/KosmosParser.spec.ts
