name: Deno CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: v1.0.0
      - run: deno run https://deno.land/std/examples/welcome.ts
